import type { CityNotes } from "../cityNotes";

/** DE translations of the city deep-dives. Keys must match EN_CITY_NOTES slugs.
 *  (Populated by translation pass.) */
export const DE_CITY_NOTES: CityNotes = {
  "singapore-sg": [
    "Singapur zählt beständig zu den teuersten Städten der Welt, doch die Kosten verteilen sich ungleichmäßig statt gleichförmig. Zwei Posten dominieren hier jedes Budget: Wohnen und Autos. Die Mieten auf dem privaten Markt sind hoch, und wer ein Auto besitzen möchte, muss zunächst ein Certificate of Entitlement erwerben, das teurer sein kann als das Fahrzeug selbst. Auch importierte Waren, Alkohol und das Essen im Restaurant tragen einen spürbaren Aufschlag.",
    "Lebenswert bleibt die Stadt, weil die Dinge des täglichen Bedarfs so günstig und so gut sind. Die MRT und die Busse sind schnell, sauber und preiswert, in den Hawker Centres bekommen Sie eine vollständige Mahlzeit für wenige Dollar, und die medizinische Versorgung ist von Weltklasse. Eine Einzelperson, die bescheiden lebt, kann ihre Ausgaben im Rahmen halten; ein Leben westlichen Zuschnitts mit privater Eigentumswohnung, Auto und häufigem Auswärtsessen ist der Punkt, an dem Singapur seinem Ruf gerecht wird. Die praktische Faustregel lautet: Treffen Sie zuerst die richtige Entscheidung beim Wohnen – alles Übrige ist dann zu bewältigen.",
  ],
  "charlotte-nc": [
    "Charlotte gehört zu den erschwinglicheren großen Städten der USA, und das ist ein wesentlicher Grund, warum es weiterhin Menschen aus den teureren Metropolen an den Küsten anzieht. Das Wohnen ist der größte Anreiz: Mieten und Immobilienpreise liegen deutlich unter denen von New York, Boston oder den kalifornischen Städten – selbst nach Jahren rasanten Wachstums. Lebensmittel, Nebenkosten und alltägliche Ausgaben bewegen sich nahe am US-Durchschnitt.",
    "Die Kompromisse sind die üblichen für eine schnell wachsende Stadt im Sun Belt. Sie werden mit ziemlicher Sicherheit ein Auto brauchen, denn der öffentliche Nahverkehr ist begrenzt, und der jüngste Zustrom neuer Einwohner hat die Mieten von einem niedrigen Ausgangsniveau aus rasch in die Höhe getrieben. Für ein mittleres Gehalt bleibt die Stadt komfortabel, und sie hat sich zu einem beliebten Ziel für Remote-Arbeitende entwickelt, die den Nordosten verlassen, um bei geringeren Wohnkosten mehr Platz zu haben.",
  ],
  "tokyo-jp": [
    "Tokios Ruf, geradezu erdrückend teuer zu sein, stimmt nur zur Hälfte. Die eigentliche Überraschung ist die Miete: Die Wohnungen sind kompakt, doch gemessen an anderen Weltmetropolen sind die Preise im Stadtzentrum durchaus moderat – deutlich niedriger als in London, New York oder Singapur. Wo sich die Kosten summieren, ist das tägliche Leben, vom Essen gehen bis zu Obst und importierten Lebensmitteln.",
    "Die Stärken der Stadt lassen sich kaum überschätzen: ein hervorragender, fair bepreister Nahverkehr, ein unübertroffener Komfort sowie Sicherheit und Gesundheitsversorgung, die zu den besten überhaupt zählen. Für Neuankömmlinge sind die größeren Hürden meist die Sprache und die Anfangskosten beim Mieten – Schlüsselgeld (key money), Kautionen und das Erfordernis eines Bürgen – und weniger das monatliche Budget. Mit einem lokalen Gehalt ist Tokio sehr gut lebbar; der Aufpreis steckt in den Extras des Lebensstils, nicht in den Grundlagen.",
  ],
  "lisbon-pt": [
    "Lissabon hat sich vom preiswertesten Hauptstadtziel Westeuropas zu einem Lehrstück darüber gewandelt, wie schnell sich das ändern kann. Die Stadt ist nach wie vor günstiger als Paris, London oder Amsterdam, doch eine Welle von Remote-Arbeitenden und die inzwischen gekappten Steuervergünstigungen (NHR) haben die Mieten im Zentrum stark nach oben getrieben – das wirklich billige Lissabon von vor einigen Jahren ist in den besten Vierteln weitgehend verschwunden, und die Einheimischen fühlen sich zunehmend aus dem Markt gedrängt.",
    "Verlassen Sie den touristischen Kern, bleibt die Stadt gemessen an Hauptstadtmaßstäben erschwinglich: Lebensmittel, Wein, Nahverkehr und Essen gehen bleiben moderat, Klima und Sicherheit sind ein echter Pluspunkt, und in Expat-Kreisen wird vielerorts Englisch gesprochen. Der entscheidende Ausschlag im Budget ist fast ausschließlich die Miete – wählen Sie ein Viertel ein paar Metrostationen außerhalb, funktioniert Lissabon noch immer; bestehen Sie auf Baixa oder Chiado, zahlen Sie beinahe Londoner Preise.",
  ],
  "dubai-ae": [
    "Dubais Verkaufsargument ist denkbar einfach: keine Einkommensteuer für Privatpersonen. Das verschiebt die gesamte Rechnung – ein gegebenes Bruttogehalt reicht weit über das hinaus, was im hochbesteuerten Europa übrig bliebe, und genau deshalb zieht die Stadt Gutverdiener und Unternehmer an. Zu Buche schlagen vor allem das Wohnen (die Jahresmiete wird oft in wenigen großen Schecks bezahlt), internationale Schulen für Familien sowie das Autofahren, denn die Stadt ist auf das Auto ausgelegt und der Nahverkehr reicht kaum über die Metro-Linie hinaus.",
    "Im Alltag decken Lebensmittel und Gastronomie die gesamte Bandbreite ab – günstig an lokalen Lokalen, schwindelerregend an der Marina –, und Alkohol trägt einen kräftigen Aufschlag. Der wahre Anreiz ist das Nettoeinkommen: Ohne Einkommensteuer und ohne Kapitalertragsteuer bleibt Ihnen weitgehend, was Sie verdienen, sodass sich in Dubai trotz hoher Mieten gut sparen lässt – vorausgesetzt, Sie übernehmen sich nicht bei Wohnkosten und Schulgebühren.",
  ],
  "bangkok-th": [
    "Bangkok zählt für jeden, der ein westliches Einkommen bezieht, zu den Großstädten mit dem besten Preis-Leistungs-Verhältnis, und ist aus gutem Grund ein fester Bestandteil der Digital-Nomad-Szene. Eine moderne Eigentumswohnung nahe der BTS oder MRT kostet einen Bruchteil einer westlichen Hauptstadt, Straßen- und einfaches Essen ist hervorragend und äußerst günstig, und das Fortkommen in der Stadt ist preiswert. Ein komfortables Leben kostet hier weit weniger als das Äquivalent in Europa oder den USA.",
    "Die Kompromisse sind die Luftqualität (besonders in der Verbrennungssaison, der sogenannten burning season), die Hitze sowie die tatsächlichen Kosten für importierte westliche Waren und internationale Schulen. Die praktische Hürde ist eher das Visum als das Geld – Thailands Langzeitoptionen haben sich verbessert, verlangen aber Planung. Für Remote-Arbeitende oder Frühruheständler bietet Bangkok einen hohen Lebensstandard bei bescheidenem Budget; für eine Familie, die auf internationale Schulbildung setzt, wird die Rechnung enger.",
  ],
  "mexico-city-mx": [
    "Mexiko-Stadt hat sich zum herausragenden Ziel für US-amerikanische Remote-Arbeitende entwickelt, und der Grund ist schlichte Arithmetik: Ein Dollar-Einkommen reicht hier außerordentlich weit. Die Mieten in gefragten Vierteln wie Roma und Condesa sind mit dem Zustrom rasch gestiegen, liegen aber immer noch deutlich unter denen jeder größeren US-Stadt, und fast alles andere – Essen, Nahverkehr, Dienstleistungen – ist dramatisch günstiger.",
    "Die Vorbehalte gelten für jede Megastadt in einem Land mittleren Einkommens: die Höhenlage, der Verkehr, die Wasserversorgung sowie eine Sicherheitslage, die von Viertel zu Viertel stark schwankt (die beliebten Expat-Gegenden sind in der Regel unbedenklich, doch Sorgfalt ist angebracht). Spanisch hilft enorm. Wer in Dollar oder Euro verdient, erhält in CDMX einen echten Großstadt-Lebensstil zu einem Bruchteil der Kosten; mit einem lokalen Gehalt sieht das Bild ganz anders aus.",
  ],
  "london-uk": [
    "London ist schlicht teuer – ohne den einseitigen Lichtblick, den Singapur oder Dubai bieten. Die Miete ist der größte Schmerzpunkt und im Großteil der Stadt gravierend; hinzu kommen hohe Transportkosten, teures Essengehen und die Council Tax, und das Budget steigt rasch. Die Gehälter liegen höher als im übrigen Vereinigten Königreich, aber selten hoch genug, um die Wohnkosten vollständig auszugleichen.",
    "Wofür Sie zahlen, sind Größe und Chancen: einer der tiefsten Arbeitsmärkte der Welt, Weltklasse-Kultur und ein zwar überfüllter, aber exzellenter Nahverkehr, der tatsächlich den Verzicht auf ein Auto erlaubt. Der wichtigste Budgethebel ist die Lage – Pendlerzonen und Außenbezirke senken die Miete erheblich, im Tausch gegen einen längeren Arbeitsweg. Für Gutverdiener geht die Rechnung auf; mit einem Durchschnittsgehalt verlangt London Kompromisse, die die meisten anderen Städte des Vereinigten Königreichs nicht fordern.",
  ],
};
