import type { CityNotes } from "../cityNotes";

/** ES translations of the city deep-dives. Keys must match EN_CITY_NOTES slugs.
 *  (Populated by translation pass.) */
export const ES_CITY_NOTES: CityNotes = {
  "singapore-sg": [
    "Singapur figura siempre entre las ciudades más caras del mundo, pero su coste es desigual más que uniforme. Dos cosas dominan cualquier presupuesto aquí: la vivienda y los coches. Los alquileres privados son elevados, y tener coche implica comprar primero un Certificado de Derecho (Certificate of Entitlement) que puede costar más que el propio vehículo. Los productos importados, el alcohol y las comidas en restaurante también arrastran un sobreprecio notable.",
    "Lo que mantiene la ciudad habitable es lo baratos y buenos que son los servicios esenciales. El MRT y los autobuses son rápidos, limpios y económicos; los hawker centres sirven comidas completas por unos pocos dólares, y la sanidad es de primer nivel. Una persona sola que viva con sobriedad puede mantener los gastos a raya; es la vida al estilo occidental —con un condominio privado, coche y salidas frecuentes a cenar— la que le da a Singapur su fama. La regla práctica: acierta primero con la decisión de la vivienda, que todo lo demás es manejable.",
  ],
  "charlotte-nc": [
    "Charlotte es una de las grandes ciudades estadounidenses más asequibles, y eso explica en buena medida por qué sigue atrayendo gente desde las metrópolis costeras más caras. La vivienda es el principal reclamo: los alquileres y los precios de compra están muy por debajo de Nueva York, Boston o las ciudades de California, incluso tras años de rápido crecimiento. La compra del supermercado, los suministros y los gastos cotidianos rondan la media de Estados Unidos.",
    "Las contrapartidas son las habituales de una ciudad del Sun Belt en pleno auge. Casi con seguridad necesitarás coche, porque el transporte público es limitado, y la reciente llegada masiva de nuevos residentes ha disparado los alquileres con rapidez desde una base baja. Para un salario de media carrera sigue siendo cómoda, y se ha convertido en un destino popular para los trabajadores remotos que dejan el noreste del país en busca de más espacio a un coste de vivienda menor.",
  ],
  "tokyo-jp": [
    "La fama de Tokio como ciudad de un coste demoledor solo es verdad a medias. El alquiler es la auténtica sorpresa: los apartamentos son compactos, pero para los estándares de una gran capital los precios del centro resultan razonables, bastante por debajo de Londres, Nueva York o Singapur. Donde se acumulan los gastos es en el día a día, desde comer fuera hasta la fruta y los comestibles importados.",
    "Las virtudes de la ciudad son difíciles de exagerar: un transporte excelente y a precio justo, una comodidad sin igual, y una seguridad y una sanidad entre las mejores del mundo. Para quien acaba de llegar, los mayores obstáculos suelen ser el idioma y el desembolso inicial del alquiler —el key money, las fianzas y la exigencia de un avalista— más que el presupuesto mensual. Con un salario local, Tokio es muy habitable; el sobreprecio está en los extras del estilo de vida, no en lo básico.",
  ],
  "lisbon-pt": [
    "Lisboa pasó de ser la capital con mejor relación calidad-precio de Europa Occidental a servir de advertencia sobre lo rápido que eso puede cambiar. Sigue siendo más barata que París, Londres o Ámsterdam, pero una oleada de trabajadores remotos y unos incentivos fiscales hoy recortados (el régimen NHR) dispararon los alquileres del centro: la Lisboa genuinamente barata de hace unos años ha desaparecido en buena medida de los barrios más codiciados, y los vecinos de toda la vida se sienten cada vez más expulsados por los precios.",
    "Aléjate del núcleo turístico y sigue siendo asequible para lo que es una capital: la comida, el vino, el transporte y salir a cenar se mantienen razonables, el clima y la seguridad son un atractivo real, y en los círculos de expatriados se habla mucho inglés. El vuelco del presupuesto es casi por completo el alquiler: elige un barrio a unas pocas paradas de metro y Lisboa aún funciona; empéñate en Baixa o Chiado y pagarás casi como en Londres.",
  ],
  "dubai-ae": [
    "El argumento de Dubái es sencillo: no hay impuesto sobre la renta de las personas físicas. Eso reconfigura todo el cálculo —un mismo salario bruto rinde mucho más que en la Europa de impuestos altos—, y por eso la ciudad atrae a quienes ganan bien y a los emprendedores. Los gastos que aprietan son la vivienda (el alquiler anual suele pagarse en unos pocos cheques de gran importe), la escolarización internacional para las familias y mantener coche, porque la ciudad está pensada para conducir y el transporte es limitado más allá de la línea de metro.",
    "En el día a día, los comestibles y la restauración abarcan todo el abanico —baratos en los locales de barrio, desorbitados en la marina— y el alcohol carga un fuerte sobreprecio. El verdadero atractivo es el salario neto: sin impuesto sobre la renta ni sobre las plusvalías, lo que ganas es en gran medida lo que te queda, así que Dubái puede ser un buen sitio para ahorrar pese a los alquileres elevados de partida, siempre que no te sobrecomprometas con la vivienda y las cuotas escolares.",
  ],
  "bangkok-th": [
    "Bangkok es una de las grandes ciudades con mejor relación calidad-precio para cualquiera que gane un sueldo occidental, y un clásico del circuito nómada digital con razón. Un apartamento moderno cerca del BTS o del MRT cuesta una fracción de lo que vale en una capital occidental, la comida callejera e informal es excelente y baratísima, y moverse resulta económico. Una vida cómoda aquí cuesta mucho menos que su equivalente en Europa o Estados Unidos.",
    "Las contrapartidas son la calidad del aire (sobre todo en la temporada de quema agrícola), el calor y el coste real de los productos occidentales importados y los colegios internacionales. Los visados suelen ser el obstáculo práctico más que el dinero: las opciones de estancia larga de Tailandia han mejorado, pero exigen planificación. Para quien trabaja en remoto o se jubila pronto, Bangkok ofrece un alto nivel de vida con un presupuesto modesto; para una familia decidida a la escolarización internacional, las cuentas se ajustan más.",
  ],
  "mexico-city-mx": [
    "Ciudad de México se ha convertido en el destino estrella de los trabajadores remotos estadounidenses, y la razón es aritmética: un ingreso en dólares cunde muchísimo aquí. El alquiler en barrios codiciados como Roma y Condesa ha subido rápido con la llegada de recién llegados, pero sigue muy por debajo de cualquier gran ciudad de Estados Unidos, y casi todo lo demás —comida, transporte, servicios— es drásticamente más barato.",
    "Las salvedades son las de cualquier megaciudad de un país de renta media: la altitud, el tráfico, la logística del agua y una seguridad que varía mucho según el barrio (las zonas populares entre expatriados suelen estar bien, pero conviene informarse). El español ayuda enormemente. Para quien gana en dólares o euros, la CDMX ofrece un auténtico estilo de vida de gran ciudad a una fracción del coste; con un salario local, el panorama es muy distinto.",
  ],
  "london-uk": [
    "Londres es, sin más, cara, sin el consuelo desigual que ofrecen Singapur o Dubái. El alquiler es el dolor principal y resulta severo en casi toda la ciudad; súmale el alto coste del transporte, lo caro de salir a cenar y el council tax (el impuesto municipal), y el presupuesto trepa deprisa. Los sueldos son más altos que en el resto del Reino Unido, pero rara vez lo bastante como para compensar del todo el golpe de la vivienda.",
    "Lo que pagas es escala y oportunidad: uno de los mercados laborales más profundos del mundo, una cultura de primer nivel y un transporte público abarrotado pero excelente que de verdad te permite prescindir del coche. La principal palanca del presupuesto es la ubicación: las zonas de cercanías y los distritos periféricos recortan el alquiler de forma notable a cambio de un trayecto más largo. Para quien gana mucho, la ciudad funciona; con un salario medio, Londres exige renuncias que la mayoría de las demás ciudades británicas no piden.",
  ],
};
