import type { CityNotes } from "../cityNotes";

/** FR translations of the city deep-dives. Keys must match EN_CITY_NOTES slugs.
 *  (Populated by translation pass.) */
export const FR_CITY_NOTES: CityNotes = {
  "singapore-sg": [
    "Singapour figure régulièrement parmi les villes les plus chères du monde, mais ce coût est déséquilibré plutôt qu'uniforme. Deux postes dominent un budget ici : le logement et la voiture. Les loyers dans le privé sont élevés, et posséder une voiture suppose d'acheter au préalable un Certificate of Entitlement qui peut coûter plus cher que le véhicule lui-même. Les produits importés, l'alcool et les repas au restaurant affichent eux aussi une prime notable.",
    "Ce qui rend la ville vivable, c'est le prix et la qualité des produits de première nécessité. Le MRT et les bus sont rapides, propres et bon marché, les hawker centres servent des repas complets pour quelques dollars, et le système de santé est de classe mondiale. Une personne seule qui vit modestement peut garder des dépenses raisonnables ; c'est avec un train de vie à l'occidentale — condo privé, voiture et sorties fréquentes au restaurant — que Singapour justifie sa réputation. La règle pratique : bien choisir son logement en premier, tout le reste se gère.",
  ],
  "charlotte-nc": [
    "Charlotte est l'une des grandes villes américaines les plus abordables, ce qui explique en grande partie pourquoi elle continue d'attirer des habitants venus de métropoles côtières plus coûteuses. Le logement est le principal atout : loyers et prix de l'immobilier se situent bien en dessous de ceux de New York, Boston ou des villes de Californie, même après des années de croissance rapide. L'alimentation, les charges et les dépenses du quotidien se rapprochent de la moyenne américaine.",
    "Les contreparties sont celles, habituelles, d'une ville de la Sun Belt en pleine expansion. Vous aurez presque certainement besoin d'une voiture, les transports en commun étant limités, et l'afflux récent de nouveaux arrivants a fait grimper les loyers rapidement à partir d'un niveau bas. Pour un salaire de milieu de carrière, la ville reste confortable, et elle est devenue un point de chute prisé des télétravailleurs qui quittent le Nord-Est pour plus d'espace à un coût de logement moindre.",
  ],
  "tokyo-jp": [
    "La réputation de Tokyo, ville d'un coût écrasant, n'est vraie qu'à moitié. Le loyer est la vraie surprise : les appartements sont compacts, mais à l'aune des grandes capitales mondiales, les prix du centre-ville sont raisonnables — bien en dessous de Londres, New York ou Singapour. C'est la vie quotidienne qui fait grimper la note, des repas au restaurant aux fruits et aux produits importés.",
    "Les atouts de la ville sont difficiles à surestimer : des transports excellents et à prix justes, une praticité inégalée, une sécurité et un système de santé parmi les meilleurs au monde. Pour les nouveaux venus, les obstacles les plus importants sont généralement la langue et le coût initial d'une location — key money, dépôts de garantie et exigence d'un garant — plutôt que le budget mensuel. Avec un salaire local, Tokyo est très vivable ; la prime se paie sur les extras du mode de vie, pas sur l'essentiel.",
  ],
  "lisbon-pt": [
    "Lisbonne est passée du statut de capitale la plus avantageuse d'Europe de l'Ouest à celui de cas d'école sur la rapidité avec laquelle une telle situation peut basculer. La ville reste moins chère que Paris, Londres ou Amsterdam, mais une vague de télétravailleurs — et des avantages fiscaux du régime RNH désormais resserrés — a fait grimper brutalement les loyers du centre : la Lisbonne réellement bon marché d'il y a quelques années a largement disparu des quartiers les plus prisés, et les habitants se sentent de plus en plus chassés par les prix.",
    "En s'éloignant du cœur touristique, elle reste abordable à l'aune des capitales : l'alimentation, le vin, les transports et les sorties au restaurant demeurent raisonnables, le climat et la sécurité sont de véritables atouts, et l'anglais est largement parlé dans les milieux expatriés. L'écart de budget tient presque entièrement au loyer — choisissez un quartier à quelques stations de métro et Lisbonne reste jouable ; exigez la Baixa ou le Chiado et vous paierez des prix proches de ceux de Londres.",
  ],
  "dubai-ae": [
    "L'argument de Dubaï est simple : aucun impôt sur le revenu des personnes physiques. Cela rebat toutes les cartes — un salaire brut donné va bien plus loin que dans une Europe fortement taxée, ce qui explique pourquoi la ville attire hauts revenus et entrepreneurs. Les postes qui pèsent sont le logement (le loyer annuel se règle souvent en quelques gros chèques), la scolarité internationale pour les familles, et la voiture, car la ville est pensée pour l'automobile et les transports restent limités au-delà de la ligne de métro.",
    "Au quotidien, courses et restaurants couvrent toute la gamme — bon marché dans les adresses locales, vertigineux du côté de la marina — et l'alcool est lourdement taxé. Le vrai attrait, c'est le salaire net : sans impôt sur le revenu ni impôt sur les plus-values, ce que vous gagnez vous reste en grande partie, si bien que Dubaï peut être un excellent endroit pour épargner malgré des loyers affichés élevés — à condition de ne pas se surengager sur le logement et les frais de scolarité.",
  ],
  "bangkok-th": [
    "Bangkok est l'une des grandes villes au meilleur rapport qualité-prix pour quiconque perçoit un revenu occidental, et un pilier du circuit des nomades numériques, à juste titre. Un condo moderne près du BTS ou du MRT coûte une fraction du prix d'une capitale occidentale, la cuisine de rue et les repas sur le pouce sont excellents et très bon marché, et les déplacements ne coûtent presque rien. Une vie confortable y revient bien moins cher que son équivalent en Europe ou aux États-Unis.",
    "Les contreparties sont la qualité de l'air (particulièrement durant la saison des brûlis), la chaleur, et le coût réel des produits occidentaux importés et des écoles internationales. Le visa est souvent l'obstacle pratique, plus que l'argent — les options de long séjour de la Thaïlande se sont améliorées mais demandent de l'anticipation. Pour un travailleur à distance ou un jeune retraité, Bangkok offre un niveau de vie élevé avec un budget modeste ; pour une famille attachée à la scolarité internationale, le calcul se resserre.",
  ],
  "mexico-city-mx": [
    "Mexico est devenue la destination phare des télétravailleurs américains, et la raison tient à l'arithmétique : un revenu en dollars y va très loin. Dans les quartiers recherchés comme Roma et Condesa, les loyers ont grimpé vite avec l'afflux, mais ils restent bien en dessous de n'importe quelle grande ville américaine, et presque tout le reste — alimentation, transports, services — est radicalement moins cher.",
    "Les réserves sont celles de toute mégapole d'un pays à revenu intermédiaire : l'altitude, la circulation, la logistique de l'eau, et une sécurité qui varie fortement d'un quartier à l'autre (les secteurs prisés des expatriés sont généralement sûrs, mais la prudence s'impose). L'espagnol aide énormément. Pour qui gagne en dollars ou en euros, CDMX offre un véritable art de vivre de grande ville pour une fraction du coût ; avec un salaire local, le tableau est tout autre.",
  ],
  "london-uk": [
    "Londres est tout simplement chère, sans la compensation déséquilibrée qu'offrent Singapour ou Dubaï. Le loyer est la douleur principale, et elle est sévère dans presque toute la ville ; ajoutez des transports coûteux, une restauration onéreuse et la council tax, et le budget grimpe vite. Les salaires y sont plus élevés que dans le reste du Royaume-Uni, mais rarement assez pour compenser entièrement le choc du logement.",
    "Ce que vous payez, c'est l'envergure et les opportunités : l'un des marchés de l'emploi les plus profonds au monde, une vie culturelle de premier plan, et des transports en commun bondés mais excellents qui permettent réellement de se passer de voiture. Le principal levier budgétaire est l'emplacement — les zones de banlieue et les boroughs périphériques réduisent sensiblement le loyer en échange d'un trajet plus long. Pour un haut revenu, la ville fonctionne ; avec un salaire moyen, Londres impose des arbitrages que la plupart des autres villes britanniques épargnent.",
  ],
};
