import type { CityNotes } from "../cityNotes";

/** PT translations of the city deep-dives. Keys must match EN_CITY_NOTES slugs.
 *  (Populated by translation pass.) */
export const PT_CITY_NOTES: CityNotes = {
  "singapore-sg": [
    "Singapura figura invariavelmente entre as cidades mais caras do mundo, mas o custo é desequilibrado, e não uniforme. Dois fatores dominam o orçamento por aqui: a habitação e os automóveis. As rendas no mercado privado são elevadas, e ter carro implica comprar primeiro um Certificate of Entitlement que pode custar mais do que o próprio veículo. Os produtos importados, o álcool e as refeições em restaurantes também têm um sobrecusto notório.",
    "O que mantém a cidade habitável é o quanto os bens essenciais são baratos e bons. O MRT e os autocarros são rápidos, limpos e económicos, os hawker centres servem refeições completas por uns poucos dólares, e os cuidados de saúde são de nível mundial. Uma pessoa sozinha a viver de forma modesta consegue manter os custos razoáveis; é num estilo de vida ocidental, com um condomínio privado, carro e saídas frequentes para jantar, que Singapura faz jus à sua fama. A regra prática: acerte primeiro na decisão da habitação — todo o resto é controlável.",
  ],
  "charlotte-nc": [
    "Charlotte é uma das grandes cidades norte-americanas mais acessíveis, o que explica em boa parte por que continua a atrair gente vinda de metrópoles costeiras mais caras. A habitação é o principal atrativo: as rendas e os preços das casas situam-se bem abaixo de Nova Iorque, Boston ou das cidades da Califórnia, mesmo após anos de crescimento acelerado. A alimentação, os serviços públicos e as despesas do dia a dia ficam próximos da média dos Estados Unidos.",
    "As contrapartidas são as habituais de uma cidade do Sun Belt em rápido crescimento. Vai quase de certeza precisar de carro, pois os transportes públicos são limitados, e a recente vaga de novos residentes fez subir as rendas depressa a partir de uma base baixa. Para um salário de meio de carreira, mantém-se confortável, e tornou-se um destino popular para trabalhadores remotos que deixam o Nordeste em busca de mais espaço a um custo de habitação mais baixo.",
  ],
  "tokyo-jp": [
    "A fama de Tóquio como cidade punitivamente cara é apenas meia verdade. A renda é a verdadeira surpresa: os apartamentos são compactos, mas, para os padrões de uma capital global, os preços no centro são razoáveis — bem abaixo de Londres, Nova Iorque ou Singapura. É na vida quotidiana que os custos se acumulam, desde comer fora até à fruta e aos produtos importados.",
    "Os pontos fortes da cidade são difíceis de exagerar: transportes excelentes e a preços justos, uma conveniência sem paralelo, e segurança e cuidados de saúde entre os melhores do mundo. Para quem chega, os maiores obstáculos costumam ser a língua e o custo inicial de arrendar — key money, depósitos e a exigência de fiador — mais do que o orçamento mensal. Com um salário local, Tóquio é muito habitável; o prémio está nos extras do estilo de vida, não no essencial.",
  ],
  "lisbon-pt": [
    "Lisboa passou de capital com melhor relação qualidade-preço da Europa Ocidental a um exemplo de como isso pode mudar depressa. Continua mais barata do que Paris, Londres ou Amesterdão, mas uma vaga de trabalhadores remotos e os benefícios fiscais do RNH — hoje restringidos — fizeram disparar as rendas no centro. A Lisboa genuinamente barata de há uns anos praticamente desapareceu nos bairros nobres, e os residentes locais sentem-se cada vez mais empurrados para fora pelos preços.",
    "Afaste-se do núcleo turístico e ainda é acessível para os padrões de uma capital: a comida, o vinho, os transportes e as refeições fora continuam razoáveis, o clima e a segurança são um atrativo real, e o inglês é amplamente falado nos círculos de expatriados. A grande variação do orçamento está quase toda na renda — escolha um bairro a algumas estações de metro do centro e Lisboa continua a compensar; insista na Baixa ou no Chiado e vai pagar quase o mesmo que em Londres.",
  ],
  "dubai-ae": [
    "O argumento do Dubai é simples: não há imposto sobre o rendimento das pessoas singulares. Isso reconfigura toda a conta — um dado salário bruto rende muito mais do que na Europa de impostos altos, e é por isso que a cidade atrai quem ganha bem e empreendedores. Os custos que pesam são a habitação (a renda anual costuma ser paga em alguns cheques avultados), as escolas internacionais para as famílias, e ter carro, já que a cidade foi feita para se conduzir e os transportes são limitados para além da linha de metro.",
    "No dia a dia, as compras e as refeições cobrem todo o espectro — baratas nos sítios locais, de cortar a respiração na marina — e o álcool tem um sobrecusto pesado. O verdadeiro atrativo é o rendimento líquido: sem imposto sobre o rendimento e sem imposto sobre mais-valias, o que ganha é, em larga medida, o que fica consigo, pelo que o Dubai pode ser um bom lugar para poupar apesar das rendas elevadas — desde que não se comprometa em excesso com a habitação e as propinas escolares.",
  ],
  "bangkok-th": [
    "Banguecoque é uma das grandes cidades com melhor relação qualidade-preço para quem aufere um rendimento ocidental, e um pilar do circuito dos nómadas digitais por boas razões. Um condomínio moderno perto do BTS ou do MRT custa uma fração do de uma capital ocidental, a comida de rua e informal é excelente e extremamente barata, e deslocar-se sai barato. Uma vida confortável aqui custa muito menos do que o equivalente na Europa ou nos Estados Unidos.",
    "As contrapartidas são a qualidade do ar (sobretudo na época das queimadas), o calor, e o custo real dos produtos ocidentais importados e das escolas internacionais. Os vistos tendem a ser o obstáculo prático mais do que o dinheiro — as opções de estadia prolongada da Tailândia melhoraram, mas exigem planeamento. Para um trabalhador remoto ou um reformado precoce, Banguecoque oferece um elevado nível de vida com um orçamento modesto; para uma família decidida a optar por ensino internacional, as contas apertam.",
  ],
  "mexico-city-mx": [
    "A Cidade do México tornou-se o destino de eleição dos trabalhadores remotos norte-americanos, e a razão é aritmética: um rendimento em dólares estica-se muito por aqui. A renda em bairros procurados como a Roma e a Condesa subiu depressa com a afluência, mas continua bem abaixo de qualquer grande cidade dos Estados Unidos, e quase tudo o resto — comida, transportes, serviços — é drasticamente mais barato.",
    "As ressalvas são as de qualquer megacidade de um país de rendimento médio: a altitude, o trânsito, a logística da água, e uma segurança que varia muito de bairro para bairro (as zonas populares entre expatriados são geralmente tranquilas, mas convém fazer o trabalho de casa). O espanhol ajuda imenso. Para quem ganha em dólares ou euros, a CDMX oferece um verdadeiro estilo de vida de grande cidade por uma fração do custo; com um salário local, o retrato é bem diferente.",
  ],
  "london-uk": [
    "Londres é simplesmente cara, sem nada do lado positivo e desequilibrado que Singapura ou o Dubai oferecem. A renda é a dor principal e é severa em quase toda a cidade; acrescente os custos elevados de transporte, as refeições fora dispendiosas e o council tax, e o orçamento sobe rapidamente. Os salários são mais altos do que no resto do Reino Unido, mas raramente o suficiente para compensar por inteiro o golpe da habitação.",
    "O que se paga é a escala e a oportunidade: um dos mercados de trabalho mais profundos do mundo, uma cultura de nível mundial, e transportes públicos excelentes, ainda que lotados, que genuinamente permitem dispensar o carro. A principal alavanca do orçamento é a localização — as zonas de commuter e os municípios periféricos reduzem bastante a renda em troca de uma viagem mais longa. Para quem ganha bem, a cidade compensa; com um salário médio, Londres exige compromissos que a maioria das outras cidades britânicas não impõe.",
  ],
};
